services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./errors.log:/app/errors.log
    networks:
      - app-network

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 10s
      retries: 20

volumes:
  redis_data:

networks:
  app-network:
      driver: bridge